/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package the.scholar;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Optimus Prime
 */
public class NewScholar extends javax.swing.JFrame {

    Connection newconn = null;
    int x=0;

    public NewScholar() {
        initComponents();
        showicon();
        newconn = DBconnect.connect();
    }

     private void showicon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/Images/main.png"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_new_main = new javax.swing.JPanel();
        panel_new_icon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_new_details = new javax.swing.JPanel();
        lbl_new_close = new javax.swing.JLabel();
        lbl_setaccount = new javax.swing.JLabel();
        txt_new_uname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txt_new_pwd = new javax.swing.JPasswordField();
        txt_new_pwdcfm = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_new_account = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(710, 480));
        setUndecorated(true);

        panel_new_main.setBackground(new java.awt.Color(255, 255, 255));
        panel_new_main.setMinimumSize(new java.awt.Dimension(710, 480));
        panel_new_main.setPreferredSize(new java.awt.Dimension(710, 480));
        panel_new_main.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_new_mainMouseDragged(evt);
            }
        });
        panel_new_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_new_mainMousePressed(evt);
            }
        });
        panel_new_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_new_icon.setBackground(new java.awt.Color(204, 0, 204));
        panel_new_icon.setPreferredSize(new java.awt.Dimension(370, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main.png"))); // NOI18N

        javax.swing.GroupLayout panel_new_iconLayout = new javax.swing.GroupLayout(panel_new_icon);
        panel_new_icon.setLayout(panel_new_iconLayout);
        panel_new_iconLayout.setHorizontalGroup(
            panel_new_iconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_new_iconLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_new_iconLayout.setVerticalGroup(
            panel_new_iconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_new_iconLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_new_main.add(panel_new_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel_new_details.setBackground(new java.awt.Color(255, 255, 255));

        lbl_new_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cross.png"))); // NOI18N
        lbl_new_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_new_closeMousePressed(evt);
            }
        });

        lbl_setaccount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_setaccount.setForeground(new java.awt.Color(204, 0, 204));
        lbl_setaccount.setText("Set your account...");

        txt_new_uname.setText("username");
        txt_new_uname.setBorder(null);
        txt_new_uname.setCaretColor(new java.awt.Color(204, 0, 204));
        txt_new_uname.setMinimumSize(new java.awt.Dimension(220, 30));
        txt_new_uname.setPreferredSize(new java.awt.Dimension(100, 100));
        txt_new_uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_new_unameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_new_unameFocusLost(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(204, 0, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 0, 204));

        jSeparator5.setBackground(new java.awt.Color(204, 0, 204));
        jSeparator5.setForeground(new java.awt.Color(204, 0, 204));

        jSeparator6.setBackground(new java.awt.Color(204, 0, 204));
        jSeparator6.setForeground(new java.awt.Color(204, 0, 204));

        txt_new_pwd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_new_pwd.setText("jPasswordField1");
        txt_new_pwd.setBorder(null);
        txt_new_pwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_new_pwdFocusGained(evt);
            }
        });

        txt_new_pwdcfm.setText("jPasswordField2");
        txt_new_pwdcfm.setBorder(null);
        txt_new_pwdcfm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_new_pwdcfmFocusGained(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/username.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/confirm.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/password.png"))); // NOI18N

        btn_new_account.setBackground(new java.awt.Color(204, 0, 204));
        btn_new_account.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_new_account.setForeground(new java.awt.Color(255, 255, 255));
        btn_new_account.setLabel("Create Account");
        btn_new_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_new_accountActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 0, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Back to login");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel_new_detailsLayout = new javax.swing.GroupLayout(panel_new_details);
        panel_new_details.setLayout(panel_new_detailsLayout);
        panel_new_detailsLayout.setHorizontalGroup(
            panel_new_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_new_detailsLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(panel_new_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_setaccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_new_close, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_new_detailsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_new_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_new_account, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_new_detailsLayout.createSequentialGroup()
                        .addGroup(panel_new_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_new_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator6)
                            .addComponent(txt_new_pwd)
                            .addComponent(txt_new_pwdcfm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txt_new_uname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );
        panel_new_detailsLayout.setVerticalGroup(
            panel_new_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_new_detailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lbl_new_close)
                .addGap(41, 41, 41)
                .addComponent(lbl_setaccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_new_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_new_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_new_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_new_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_new_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_new_pwdcfm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_new_account, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        panel_new_main.add(panel_new_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 340, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_new_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel_new_main, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(710, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_new_closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_new_closeMousePressed
        System.exit(0);
    }//GEN-LAST:event_lbl_new_closeMousePressed
    int xx, xy;
    private void panel_new_mainMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_new_mainMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_panel_new_mainMouseDragged

    private void panel_new_mainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_new_mainMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_panel_new_mainMousePressed

    private void txt_new_unameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_new_unameFocusGained
        txt_new_uname.setText("");
    }//GEN-LAST:event_txt_new_unameFocusGained

    private void txt_new_pwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_new_pwdFocusGained
        txt_new_pwd.setText("");
    }//GEN-LAST:event_txt_new_pwdFocusGained

    private void txt_new_pwdcfmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_new_pwdcfmFocusGained
        txt_new_pwdcfm.setText("");
    }//GEN-LAST:event_txt_new_pwdcfmFocusGained

    private void btn_new_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_new_accountActionPerformed
       if (txt_new_pwd.getText().equals(txt_new_pwdcfm.getText())){
            if (x==0){
            try {
            String query;
            query = "INSERT INTO main.passbook (id,uname,pass) VALUES (?,?,?)";
            PreparedStatement pst=newconn.prepareStatement(query);
            pst.setString(1,null);
            pst.setString(2,txt_new_uname.getText());
            pst.setString(3,txt_new_pwd.getText());
            pst.execute();
            pst.close();
            OptionDisplay op=new OptionDisplay();
            op.successcreate();
             txt_new_uname.setText("username");
             txt_new_pwd.setText("sfgerteryry");
             txt_new_pwdcfm.setText("sfgerteryry");
            
        } catch (Exception e) {
            
            OptionDisplay op=new OptionDisplay();
            String error=e.getMessage();
            op.dbFailed(error);
        }
        }
        else{
            OptionDisplay op=new OptionDisplay();
            op.showcustom("User already Exists. Contact Administrator");
            txt_new_uname.setText("username");
             txt_new_pwd.setText("sfgerteryry");
             txt_new_pwdcfm.setText("sfgerteryry");
        }
        
       }
       
       else{
           OptionDisplay op=new OptionDisplay();
           op.pwdWarning("Password Mismatched");
            txt_new_uname.setText("username");
             txt_new_pwd.setText("sfgerteryry");
             txt_new_pwdcfm.setText("sfgerteryry");
       }
    }//GEN-LAST:event_btn_new_accountActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
       LoginScholar lc=new LoginScholar();
       this.dispose();
       lc.setVisible(true);
    }//GEN-LAST:event_jLabel2MousePressed

    private void txt_new_unameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_new_unameFocusLost
        String uname= txt_new_uname.getText();
        String query = "select uname from main.passbook where uname='"+uname+"';";
        try {
            PreparedStatement pst = newconn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            boolean empty = true;
            while (rs.next()) {
                empty = false;
                x=1;
            }

            if (empty) {
                x=0;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_txt_new_unameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewScholar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewScholar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewScholar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewScholar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewScholar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_new_account;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbl_new_close;
    private javax.swing.JLabel lbl_setaccount;
    private javax.swing.JPanel panel_new_details;
    private javax.swing.JPanel panel_new_icon;
    private javax.swing.JPanel panel_new_main;
    private javax.swing.JPasswordField txt_new_pwd;
    private javax.swing.JPasswordField txt_new_pwdcfm;
    private javax.swing.JTextField txt_new_uname;
    // End of variables declaration//GEN-END:variables
}
