/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package the.scholar;

import java.awt.Toolkit;

/**
 *
 * @author Optimus Prime
 */
public class OptionDisplay extends javax.swing.JFrame {

    /**
     * Creates new form OptionDisplay
     */
    public OptionDisplay() {
        initComponents();
        showicon();

    }
    
    private void showicon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/Images/main.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_option_display = new javax.swing.JLabel();
        btn_option_close = new java.awt.Button();
        lbl_option_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbl_option_display.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_option_display.setForeground(new java.awt.Color(204, 0, 204));
        lbl_option_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_option_close.setBackground(new java.awt.Color(204, 0, 204));
        btn_option_close.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_option_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_option_close.setLabel("Close");
        btn_option_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_option_closeActionPerformed(evt);
            }
        });

        lbl_option_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warning.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_option_display, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_option_icon)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_option_close, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_option_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(lbl_option_display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_option_close, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(494, 154));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_option_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_option_closeActionPerformed
        dispose();
    }//GEN-LAST:event_btn_option_closeActionPerformed

    public void Warning() {
        lbl_option_display.setFont(new java.awt.Font("Segoe UI", 0, 15)); 
        lbl_option_display.setForeground(new java.awt.Color(255, 0, 0));
        lbl_option_display.setText("Username or Password is incorrect!!!");
        lbl_option_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warning.png")));
        this.setVisible(true);
    }
    public void pwdWarning(String s) {
        lbl_option_display.setFont(new java.awt.Font("Segoe UI", 0, 15)); 
        lbl_option_display.setForeground(new java.awt.Color(255, 0, 0));
        lbl_option_display.setText(s);
        lbl_option_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warning.png"))); 
        this.setVisible(true);
    }

    public void successcreate() {
        lbl_option_display.setFont(new java.awt.Font("Segoe UI", 0, 15)); 
        lbl_option_display.setForeground(new java.awt.Color(204, 0, 204));
        lbl_option_display.setText("Account Created");
        lbl_option_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Success.png")));
        this.setVisible(true);
    }
    
     public void successStudentCreate() {
        lbl_option_display.setFont(new java.awt.Font("Segoe UI", 0, 15)); 
        lbl_option_display.setForeground(new java.awt.Color(204, 0, 204));
        lbl_option_display.setText("New  student entry added to database");
        lbl_option_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Success.png")));
        this.setVisible(true);
    }
    
    public void forgetpass() {
        lbl_option_display.setFont(new java.awt.Font("Segoe UI", 0, 15)); 
        lbl_option_display.setForeground(new java.awt.Color(204, 0, 204));
        lbl_option_display.setText("Please contact administrator to reset the password");
        lbl_option_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resetpass.png")));
        this.setVisible(true);
    }
    public void dbFailed(String e) {
        lbl_option_display.setFont(new java.awt.Font("Segoe UI", 0, 10)); 
        lbl_option_display.setForeground(new java.awt.Color(255, 0, 0));
        lbl_option_display.setText(e);
        lbl_option_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warning.png"))); 
        this.setVisible(true);
    }
    
     public void loginSuccess( String name) {
        lbl_option_display.setFont(new java.awt.Font("Segoe UI", 0, 16)); 
        lbl_option_display.setForeground(new java.awt.Color(0,104, 0));
        lbl_option_display.setText("You have successfully logged in as "+name);
        lbl_option_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Success.png"))); 
        this.setVisible(true);
    }
     
     
       public void Success( ) {
        lbl_option_display.setFont(new java.awt.Font("Segoe UI", 0, 16)); 
        lbl_option_display.setForeground(new java.awt.Color(0,104, 0));
        lbl_option_display.setText("Database Updated");
        lbl_option_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AddEntry.png"))); 
        this.setVisible(true);
    }
       
       public void printf( ) {
        lbl_option_display.setFont(new java.awt.Font("Segoe UI", 0, 16)); 
        lbl_option_display.setForeground(new java.awt.Color(0,104, 0));
        lbl_option_display.setText("Pdf successfully created as /Result.pdf");
        lbl_option_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AddEntry.png"))); 
        this.setVisible(true);
    }
       
       public void showcustom(String e) {
        lbl_option_display.setFont(new java.awt.Font("Segoe UI", 0, 12)); 
        lbl_option_display.setForeground(new java.awt.Color(255, 0, 0));
        lbl_option_display.setText(e);
        lbl_option_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warning.png"))); 
        this.setVisible(true);
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_option_close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_option_display;
    private javax.swing.JLabel lbl_option_icon;
    // End of variables declaration//GEN-END:variables

   

    
}
