/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package the.scholar;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Optimus Prime
 */
public class ScholarPrint extends javax.swing.JFrame {

    Connection conn = null;

    public ScholarPrint() {
        initComponents();
        conn = DBconnect.connect();
        showtable();
        showicon();
    }
    
     private void showicon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/Images/main.png"));
    }

    public void username(String name) {
        lbl_activename.setFont(new java.awt.Font("Segoe UI", 0, 12));
        lbl_activename.setForeground(new java.awt.Color(255, 255, 255));
        lbl_activename.setText(name);
    }

    public void showtable() {
        try {
            String query = "select * from main.StudentDB";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            String err = e.getMessage();
            OptionDisplay op = new OptionDisplay();
            op.dbFailed(err);
        }

    }

    public void Calculate() {

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            int row = i;
            txt_rollno.setText(jTable1.getModel().getValueAt(row, 1).toString());
            lbl_name.setText(jTable1.getModel().getValueAt(row, 2).toString());
            txt_online1.setText(jTable1.getModel().getValueAt(row, 3).toString());
            txt_online2.setText(jTable1.getModel().getValueAt(row, 4).toString());
            txt_classPer.setText(jTable1.getModel().getValueAt(row, 5).toString());
            txt_viva.setText(jTable1.getModel().getValueAt(row, 6).toString());
            txt_obsn.setText(jTable1.getModel().getValueAt(row, 8).toString());
            txt_attendance.setText(jTable1.getModel().getValueAt(row, 7).toString());

            Integer rollno = Integer.valueOf(txt_rollno.getText());
            Double online1 = Double.valueOf(txt_online1.getText()) * 25 / 100;
            Double online2 = Double.valueOf(txt_online2.getText()) * 25 / 100;
            Double classper = Double.valueOf(txt_classPer.getText()) * 20 / 100;
            Double viva = Double.valueOf(txt_viva.getText()) * 10 / 100;
            Double obsn = Double.valueOf(txt_obsn.getText()) * 10 / 100;
            Double attendance = Double.valueOf(txt_attendance.getText()) * 10 / 100;
            
            if (online1 < 0) {
                online1 = 0.0;
            }
            if (online2 < 0) {
                online2 = 0.0;
            }
            if (classper < 0) {
                classper = 0.0;
            }
            if (viva < 0) {
                viva = 0.0;
            }
            if (obsn < 0) {
                obsn = 0.0;
            }
            if (attendance < 0) {
                attendance = 0.0;
            }

            System.out.println(online1 + " " + online2 + " " + classper + " " + viva + " " + obsn + " " + attendance);
            Double total = online1 + online2 + classper + viva + obsn + attendance;
            System.out.println(total);

            Double GPA = calcgpa(total);
            String ltrgrade = calcltrgrade(total);

            try {
                //String query = "UPDATE main.StudentDB SET total=  '" + total.doubleValue() + "' WHERE serial= '" + (i + 1) + "';";
                String query = "update main.StudentDB set total='" + total + "', gradepoint='" + GPA + "',ltrgrade='" + ltrgrade + "'WHERE serial= '" + (i + 1) + "';";
                System.out.println(query);
                System.out.println();
                PreparedStatement pst = conn.prepareStatement(query);
                int rs = pst.executeUpdate();
                OptionDisplay op = new OptionDisplay();
                //op.Success();
                pst.close();
            } catch (Exception e) {
                String err = e.getMessage();
                OptionDisplay op = new OptionDisplay();
                op.dbFailed(err);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_print_main = new javax.swing.JPanel();
        panel_navigation = new javax.swing.JPanel();
        lbl_newStudent = new javax.swing.JLabel();
        Lbl_edit = new javax.swing.JLabel();
        lbl_print = new javax.swing.JLabel();
        lbl_print1 = new javax.swing.JLabel();
        panel_Banner = new javax.swing.JPanel();
        lbl_icon = new javax.swing.JLabel();
        lbl_activename = new javax.swing.JLabel();
        lbl_subheading = new javax.swing.JLabel();
        lbl_heading = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_printmain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_rollno = new javax.swing.JLabel();
        txt_classPer = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_name = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_online1 = new javax.swing.JTextField();
        txt_viva = new javax.swing.JTextField();
        txt_online2 = new javax.swing.JTextField();
        txt_obsn = new javax.swing.JTextField();
        lbl_update_entry = new javax.swing.JLabel();
        lbl_del_entry = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_Attendance = new javax.swing.JLabel();
        txt_attendance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_print_main.setBackground(new java.awt.Color(255, 255, 255));
        panel_print_main.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_print_mainMouseDragged(evt);
            }
        });
        panel_print_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_print_mainMousePressed(evt);
            }
        });

        panel_navigation.setBackground(new java.awt.Color(255, 255, 255));

        lbl_newStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AddStudent.png"))); // NOI18N
        lbl_newStudent.setToolTipText("New Student");
        lbl_newStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_newStudentMousePressed(evt);
            }
        });

        Lbl_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png"))); // NOI18N
        Lbl_edit.setToolTipText("Insert Data");
        Lbl_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lbl_editMousePressed(evt);
            }
        });

        lbl_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View selected.png"))); // NOI18N
        lbl_print.setToolTipText("Quick Edit");

        lbl_print1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Print.png"))); // NOI18N
        lbl_print1.setToolTipText("View And Print");
        lbl_print1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_print1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel_navigationLayout = new javax.swing.GroupLayout(panel_navigation);
        panel_navigation.setLayout(panel_navigationLayout);
        panel_navigationLayout.setHorizontalGroup(
            panel_navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navigationLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_print)
                    .addComponent(Lbl_edit)
                    .addComponent(lbl_newStudent)
                    .addComponent(lbl_print1))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panel_navigationLayout.setVerticalGroup(
            panel_navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_newStudent)
                .addGap(18, 18, 18)
                .addComponent(Lbl_edit)
                .addGap(18, 18, 18)
                .addComponent(lbl_print)
                .addGap(18, 18, 18)
                .addComponent(lbl_print1)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        panel_Banner.setBackground(new java.awt.Color(204, 0, 204));

        lbl_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banner.png"))); // NOI18N

        lbl_activename.setBackground(new java.awt.Color(255, 255, 255));
        lbl_activename.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl_activename.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Ok_24px.png"))); // NOI18N
        lbl_activename.setText("remon");

        lbl_subheading.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_subheading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_subheading.setText("Student Grarebook Application");

        lbl_heading.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbl_heading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_heading.setText("The Scholar");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel_BannerLayout = new javax.swing.GroupLayout(panel_Banner);
        panel_Banner.setLayout(panel_BannerLayout);
        panel_BannerLayout.setHorizontalGroup(
            panel_BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BannerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_icon)
                .addGap(36, 36, 36)
                .addGroup(panel_BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_BannerLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(lbl_subheading, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(457, 457, 457)
                .addGroup(panel_BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lbl_activename))
                .addContainerGap())
        );
        panel_BannerLayout.setVerticalGroup(
            panel_BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BannerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_icon))
            .addGroup(panel_BannerLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lbl_subheading))
            .addComponent(lbl_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panel_BannerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_activename))
        );

        panel_printmain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Roll No:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Class Prerformance:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Online 1:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Online 2:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Viva:");

        txt_rollno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_classPer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 0, 255));
        jSeparator1.setForeground(new java.awt.Color(204, 0, 204));

        lbl_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Observation:");

        txt_online1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_viva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_online2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_obsn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbl_update_entry.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbl_update_entry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update.png"))); // NOI18N
        lbl_update_entry.setText("Update");
        lbl_update_entry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_update_entryMousePressed(evt);
            }
        });

        lbl_del_entry.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbl_del_entry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        lbl_del_entry.setText("Delete");
        lbl_del_entry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_del_entryMousePressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        lbl_Attendance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Attendance.setText("Attendance:");

        txt_attendance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh.png"))); // NOI18N
        jLabel7.setText("Refresh");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel_printmainLayout = new javax.swing.GroupLayout(panel_printmain);
        panel_printmain.setLayout(panel_printmainLayout);
        panel_printmainLayout.setHorizontalGroup(
            panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_printmainLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_printmainLayout.createSequentialGroup()
                        .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_printmainLayout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(jLabel7)
                                .addGap(46, 46, 46)
                                .addComponent(lbl_update_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_del_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_printmainLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(261, 261, 261)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_printmainLayout.createSequentialGroup()
                        .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_classPer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_viva, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_printmainLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_online1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_printmainLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_obsn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_printmainLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(txt_online2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_printmainLayout.createSequentialGroup()
                                .addComponent(lbl_Attendance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(146, 146, 146))))
            .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_printmainLayout.createSequentialGroup()
                    .addContainerGap(31, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        panel_printmainLayout.setVerticalGroup(
            panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_printmainLayout.createSequentialGroup()
                .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_printmainLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_printmainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_classPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_online1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_online2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_viva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_obsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_attendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_del_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_update_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(68, 68, 68))
            .addGroup(panel_printmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_printmainLayout.createSequentialGroup()
                    .addContainerGap(167, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(117, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panel_print_mainLayout = new javax.swing.GroupLayout(panel_print_main);
        panel_print_main.setLayout(panel_print_mainLayout);
        panel_print_mainLayout.setHorizontalGroup(
            panel_print_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_print_mainLayout.createSequentialGroup()
                .addComponent(panel_navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_printmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panel_Banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_print_mainLayout.setVerticalGroup(
            panel_print_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_print_mainLayout.createSequentialGroup()
                .addComponent(panel_Banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_print_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_printmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_print_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_print_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1058, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_newStudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_newStudentMousePressed
        AddStudent as = new AddStudent();
        as.username(lbl_activename.getText());
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_newStudentMousePressed

    private void Lbl_editMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_editMousePressed
        MainSheet m = new MainSheet();
        m.username(lbl_activename.getText());
        m.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_Lbl_editMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel1MousePressed
    int xx, xy;
    private void panel_print_mainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_print_mainMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_panel_print_mainMousePressed

    private void panel_print_mainMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_print_mainMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_panel_print_mainMouseDragged

    private void lbl_update_entryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_update_entryMousePressed
        try {

            Integer rollno = Integer.valueOf(txt_rollno.getText());
            Double online1 = Double.valueOf(txt_online1.getText());
            Double online2 = Double.valueOf(txt_online2.getText());
            Double classper = Double.valueOf(txt_classPer.getText());
            Double viva = Double.valueOf(txt_viva.getText());
            Double obsn = Double.valueOf(txt_obsn.getText());
            Double attendance = Double.valueOf(txt_attendance.getText());
            String sql = "update main.StudentDB set classper='" + classper.doubleValue() + "', online1='" + online1.doubleValue() + "',online2='" + online2.doubleValue() + "',attendance='" + attendance.doubleValue() + "', viva='" + viva.doubleValue() + "',obsn='" + obsn.doubleValue() + "'WHERE rollno = '" + rollno + "';";
            //String sql="UPDATE main.StudentDB SET classper=  '" + classper.doubleValue() + "' WHERE rollno = '" + rollno + "';"; 
            PreparedStatement pst = conn.prepareStatement(sql);
            int rs = pst.executeUpdate();
            OptionDisplay op = new OptionDisplay();
            op.Success();
            showtable();
            Calculate();
            showtable();
            pst.close();
        } catch (Exception ex) {
            String err = ex.getMessage();
            OptionDisplay op = new OptionDisplay();
            op.dbFailed(err);

        }
//        Calculate();
//        showtable();
    }//GEN-LAST:event_lbl_update_entryMousePressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        txt_rollno.setText(jTable1.getModel().getValueAt(row, 1).toString());
        lbl_name.setText(jTable1.getModel().getValueAt(row, 2).toString());
        txt_online1.setText(jTable1.getModel().getValueAt(row, 3).toString());
        txt_online2.setText(jTable1.getModel().getValueAt(row, 4).toString());
        txt_classPer.setText(jTable1.getModel().getValueAt(row, 5).toString());
        txt_viva.setText(jTable1.getModel().getValueAt(row, 6).toString());
        txt_obsn.setText(jTable1.getModel().getValueAt(row, 8).toString());
        txt_attendance.setText(jTable1.getModel().getValueAt(row, 7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void lbl_del_entryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_del_entryMousePressed
        try {
            String query;
            query = "DELETE FROM main.StudentDB WHERE rollno='" + txt_rollno.getText() + "';";
            PreparedStatement pst = conn.prepareStatement(query);
            //pst.setString(2,txt_roll.getText());
            int rs = pst.executeUpdate();
            OptionDisplay op = new OptionDisplay();
            op.showcustom("Student recored Deleted");
        } catch (Exception e) {

            OptionDisplay op = new OptionDisplay();
            String error = e.getMessage();
            op.dbFailed(error);
        }
        showtable();
    }//GEN-LAST:event_lbl_del_entryMousePressed

    private void lbl_print1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_print1MousePressed
        PrintMain pm = new PrintMain();
        pm.username(lbl_activename.getText());
        pm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_print1MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        Calculate();
        showtable();
    }//GEN-LAST:event_jLabel7MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScholarPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScholarPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScholarPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScholarPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScholarPrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_Attendance;
    private javax.swing.JLabel lbl_activename;
    private javax.swing.JLabel lbl_del_entry;
    private javax.swing.JLabel lbl_heading;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_newStudent;
    private javax.swing.JLabel lbl_print;
    private javax.swing.JLabel lbl_print1;
    private javax.swing.JLabel lbl_subheading;
    private javax.swing.JLabel lbl_update_entry;
    private javax.swing.JPanel panel_Banner;
    private javax.swing.JPanel panel_navigation;
    private javax.swing.JPanel panel_print_main;
    private javax.swing.JPanel panel_printmain;
    private javax.swing.JTextField txt_attendance;
    private javax.swing.JTextField txt_classPer;
    private javax.swing.JTextField txt_obsn;
    private javax.swing.JTextField txt_online1;
    private javax.swing.JTextField txt_online2;
    private javax.swing.JLabel txt_rollno;
    private javax.swing.JTextField txt_viva;
    // End of variables declaration//GEN-END:variables

    private Double calcgpa(Double total) {
        Double gpa = 0.0;
        if (total >= 80) {
            gpa = 4.0;
        } else if (total >= 75 && total < 80) {
            gpa = 3.75;
        } else if (total >= 70 && total < 75) {
            gpa = 3.50;
        } else if (total >= 65 && total < 70) {
            gpa = 3.25;
        } else if (total >= 60 && total < 65) {
            gpa = 3.00;
        } else if (total >= 55 && total < 60) {
            gpa = 2.75;
        } else if (total >= 50 && total < 55) {
            gpa = 2.50;
        } else if (total >= 45 && total < 50) {
            gpa = 2.25;
        } else if (total >= 40 && total < 45) {
            gpa = 2.00;
        } else {
            gpa = 0.0;
        }

        return gpa;
    }

    private String calcltrgrade(Double total) {
        String gp = "";
        if (total >= 80) {
            gp = "A+";
        } else if (total >= 75 && total < 80) {
            gp = "A";
        } else if (total >= 70 && total < 75) {
            gp = "A-";
        } else if (total >= 65 && total < 70) {
            gp = "B+";
        } else if (total >= 60 && total < 65) {
            gp = "B";
        } else if (total >= 55 && total < 60) {
            gp = "B-";
        } else if (total >= 50 && total < 55) {
            gp = "C+";
        } else if (total >= 45 && total < 50) {
            gp = "C";
        } else if (total >= 40 && total < 45) {
            gp = "D";
        } else {
            gp = "F";
        }

        return gp;
    }
}
